Data_Preparation:
  test_size: 0.20
  random_state: 28

Train:
  Random_Forest:
    n_estimators: 320
    criterion: 'squared_error'
    max_depth: 29
    max_features: null
    min_samples_split: 6
    min_samples_leaf: 5
    max_samples: 0.6966716265758868
    verbose: 1
    n_jobs: -1
  
  LightGBM:
    n_estimators: 189
    max_depth: 26
    learning_rate: 0.6487576851269139
    subsample: 0.879352229490535
    min_child_weight: 16
    min_split_gain: 0.037263001442866345
    reg_lambda: 28.864188304904502
    n_jobs: -1